### ISSUE TITLE
add ability to block, or not, depending on hostname

### ISSUE THREAD

**Issue by linuxcaffe** [tbabej/taskwarrior-block-recurrence-hook#2]
because I'm trying to share taskrc, configs, hooks etc between installations, using this hook (or the built-in equivalent config) would apply to all installations. I think it would be optimal (for me) to have a block-recurrence-hook that blocked (or not) depending on the hostname.

**Comment by tbabej** [comment]
This hook is deprecated (and does not work anymore), hence not an ideal solution to this problem.
